spring.application.name=intelimix

server.port=8094
# 1. Database Connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/commodity_db

# 2. Database Credentials (Separated onto unique lines)
spring.datasource.username=noluth
spring.datasource.password=$auberave#

# 3. JDBC Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Spring ORM / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

# 5. SQL Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


